language: python
python:
  - "3.5"
branches:
  only:
  - master
install:
- echo "installing"
script:
- |
  pip install -r requirements.txt
  python -m pytest -m "not integration_elastic_search"
- #make clean

env:
global:

