FILE_SERVICE_URL = "localhost:"
ELASTIC_URL = "http://localhost:9200"
ELASTIC_SOURCE_IMAGES_INDEX = "index"
ELASTIC_SOURCE_IMAGES_TYPE = "sources"
ELASTIC_FACES_INDEX = "index"
ELASTIC_FACES_TYPE = "faces"
ELASTIC_DESCRIPTOR_INDEX = "index"
ELASTIC_DESCRIPTOR_TYPE = "descriptors"

